// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDIpn4myHSyR4UnG7BekMqG0Me7sb3iLU',
    appId: '1:370276479498:web:681c426281ea2f2fb8a5f3',
    messagingSenderId: '370276479498',
    projectId: 'proof-of-concept-de7fe',
    authDomain: 'proof-of-concept-de7fe.firebaseapp.com',
    storageBucket: 'proof-of-concept-de7fe.appspot.com',
    measurementId: 'G-8S3564KS94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwWe8O1T0yINqpjOvlCP9DuyLRrrf8knQ',
    appId: '1:370276479498:android:502808c3284d7575b8a5f3',
    messagingSenderId: '370276479498',
    projectId: 'proof-of-concept-de7fe',
    storageBucket: 'proof-of-concept-de7fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIHfk5c3GP-eeFwqDom-jCrrTCNIi8Ts4',
    appId: '1:370276479498:ios:71e455aa8d85a8ceb8a5f3',
    messagingSenderId: '370276479498',
    projectId: 'proof-of-concept-de7fe',
    storageBucket: 'proof-of-concept-de7fe.appspot.com',
    iosBundleId: 'com.example.socialNetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIHfk5c3GP-eeFwqDom-jCrrTCNIi8Ts4',
    appId: '1:370276479498:ios:71e455aa8d85a8ceb8a5f3',
    messagingSenderId: '370276479498',
    projectId: 'proof-of-concept-de7fe',
    storageBucket: 'proof-of-concept-de7fe.appspot.com',
    iosBundleId: 'com.example.socialNetwork',
  );
}
